### PR TITLE
Removing apostraphe escaping

### PR DESCRIPTION
**Pull request by itamarwe**
Referring to https://github.com/Neamar/featureless-job-queue/issues/3

### CODE REVIEW

**Comment by Neamar** [comment]
Thanks for the PR, closing this issue and I'll have a look at why I was escaping them in the first place -- I seem to remember it had something to do with sending the command to Redis

**Comment by Neamar** [comment]
You're right -- it is indeed a bug.

I'm lucky my data is alphanumeric only ;)

Thanks!

**Comment by Neamar** [comment]
Published as v1.0.4

**Comment by itamarwe** [comment]
De rien ;)

**Pull request merged**
